services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sre-production-app
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://avijit:Avijitpal%401@database.dlwecr7.mongodb.net/?retryWrites=true&w=majority&appName=Database
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sre-network

  db:
    image: mongo:7.0-jammy
    container_name: sre-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sre-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  sre-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
