apiVersion: v1
kind: Secret
metadata:
  name: sre-service-secret
  labels:
    app: sre-service
type: Opaque
stringData:
  DB_PASSWORD: "SuperSecureClusterPassword123!"
  API_KEY: "sre-prod-api-key-xyz"
